mode: rollout

data_path: ./datasets/out_fluid_kaggle/
scenario: fluid
scenario_options:
  fluid:
    dataset: ./datasets/out_fluid_kaggle/dam_break_left
    rollout_dataset: valid
model_path: ./kaggle_models/
output_path: ./kaggle_rollouts/
output_filename: rollout

model_file: latest
rollout_inference_max_examples: 4
noise_std: 0.0003
cuda_device_number: null
