mode: train

data_path: ./kaggle_output/out_fluid/
scenario: fluid
scenario_options:
  fluid:
    dataset: ./kaggle_output/out_fluid/dam_break_left
    rollout_dataset: valid
    description: Kaggle-friendly dam break dataset
model_path: ./kaggle_models/
output_path: ./kaggle_rollouts/
output_filename: rollout

batch_size: 2
noise_std: 0.0003

ntraining_steps: 1500
validation_interval: 500
nsave_steps: 500
rollout_interval: null
rollout_max_examples: 1
rollout_dataset: null
train_dataset_fraction: null
valid_dataset_fraction: null
train_dataset_count: null
valid_dataset_count: null
tensorboard_log_dir: null
log_interval: 100
tensorboard_interval: null
tensorboard_port: null
tensorboard_host: null

lr_init: 0.0001
lr_decay: 0.1
lr_decay_steps: 5000000

model_file: null
train_state_file: null

cuda_device_number: null
