mode: train
data_path: ./datasets/out/
method: gns
method_options: {}
model_path: ./models/test_run/
output_path: ./rollouts/test_run/
output_filename: rollout

batch_size: 2
noise_std: 0.00067
noise: random_walk
loss: acceleration

ntraining_steps: 100
validation_interval: null
nsave_steps: 50
log_interval: 10
rollout_interval: 50
rollout_max_examples: 1
rollout_dataset: valid
train_dataset_fraction: 0.5
valid_dataset_fraction: 0.5
train_dataset_count: null
valid_dataset_count: null
tensorboard_enable: true
tensorboard_log_dir: ./models/test_run/tb
tensorboard_interval: 10
tensorboard_port: 6006
tensorboard_host: 127.0.0.1

lr_init: 0.0001
lr_decay: 0.1
lr_decay_steps: 1000

model_file: null
train_state_file: null

cuda_device_number: null
